### ISSUE TITLE
TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by Feriixu** [carl-mastrangelo/gammux#1]
`C:\Users\krade\go\src\gammux>python gammux.py fine.jpg notfine.jpg dest.png
Traceback (most recent call last):
  File "gammux.py", line 63, in <module>
    full = full.resize((thumb.size[0] / 2, thumb.size[1] / 2), Image.LANCZOS)
  File "C:\Users\krade\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", line 1806, in resize
    return self._new(self.im.resize(size, resample, box))
TypeError: integer argument expected, got float`

This is the full error.

**Comment by Feriixu** [comment]
I was using Python 3 instead of 2 *facepalm*

**Comment by carl-mastrangelo** [comment]
Whoops, I should probably upgrade the script to Python 2.   

Also FYI:  There's a pure browser version of this:    https://carlmastrangelo.com/apps/gamma-muxing-in-browser
